[package]
name = "maze-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
druid = { version = "0.8.3" }
rand = "0.8.5"
